### ISSUE TITLE
Slight jankiness on Brutstrap theme

### ISSUE THREAD

**Issue by ejheil** [jfmcbrayer/brutaldon#50]
Broken image, weird text positioning

![image](https://user-images.githubusercontent.com/1548508/52344244-42b7bd00-29e8-11e9-9b65-b18b92fd3fec.png)

**Comment by jfmcbrayer** [comment]
I've seen the broken image on other themes, so it's not brutstrap-specific. I'm thinking that it has to do with you changing your avatar; it's keeping the link to your old one, which is now broken. Logging out and back in should fix it.

The weird text positioning is just the alt-text being aligned with where the image would be placed rather than the other text.

**Comment by ejheil** [comment]
Thanks, logging out and back in fixed it.
