### ISSUE TITLE
feature request: a way to get to one's own profile

### ISSUE THREAD

**Issue by codl** [jfmcbrayer/brutaldon#59]
it'd be convenient if say, one's avatar in the compose form, or in the top left, led to one's profile page

I often want to get to my own profile to reply to one of my own threads

**Comment by jfmcbrayer** [comment]
The avatar in the top left is out – it needs to go to the home timeline, just because that's what people expect from the "brand" icon in typical web app layouts, and also because it makes the default theme on mobile more usable. But I making the avatar in the compose form go to your own profile is perfectly reasonable.

**Comment by jfmcbrayer** [comment]
Fixed - avatar in compose form goes to your own profile.
